### PR TITLE
Fix getVideoInfoTag error

### LINKED ISSUE #2050: 3.9.1 bug when playing media: 'Nonetype' object has no attribute 'setpath'
Hello,

i have a bug since updating to 3.9.1 on coreelec 20.5: whenever i try to play a media i have: "Nonetype object has no attribute set path"
I tried restart and reset database (incl. app config), still the same

Here is my [log](https://paste.coreelec.org/uLJI26)

Thank you

### PR DESCRIPTION
**Pull request by Spacetech**
Fixes #2050

The `PKCListItem` object does not implement `getVideoInfoTag` ([link](https://github.com/croneter/PlexKodiConnect/blob/f76c4dddab544503d5f6f4182c1dec53213d25fe/resources/lib/transfer.py#L261))

This PR updates the logic to skip calling `getVideoInfoTag` for this case. I don't have a local repro for this, but it should work

### CODE REVIEW

**Comment by croneter** [comment]
Thanks @Spacetech, once again! Worked on my installation.
