### ISSUE TITLE
Movies don't show up in a Kodi set/collection

### ISSUE THREAD

**Issue by milesbenson** [croneter/PlexKodiConnect#689]
Hi there,

i created some new movie collections in Plex yesterday, but several syncs later, they still dont show up in Kodi with plexkodiconnect. Older sets are showing up as expected. I had to repair the local database to make the new sets showing up.

What am i missing? I do not have background sync enabled and plexkodiconnect is syncing every five minutes.

**Comment by croneter** [comment]
Never mind, found the issue: if all movies are already in the Plex library and synched to PKC/Kodi and you create a new Plex collection later, Plex does not mark the movie as "changed". Obviously, there's no way for PKC to pick up on this. 

# Workaround
In the PKC settings under Advanced, hit `Repair the Kodi database (force update all content)`.

A permanent fix to this requires quite a lot of code 😞

**Comment by milesbenson** [comment]
Ok, as i stated before, repairing the database did fix the issue, that is unfortunately what i expected, but an understandable behaviour :) Thank you for the fast help. As i am managing the movie-sets myself, it's not a big deal as i know i have to repair the db afterwars 👍

**Comment by Nojahhh** [comment]
I still can't get it to work. A lot of my collections are missing a lot of movies. My Pixar collection have 20 movies but only 14 show up in Kodi. And the wierd thing is that a movie thats missing in one collection might show up in another one that it is in. I've tried to repair the db and reset as much as I could through Kodi/CoreELEC. In all other clients I have connected to Plex they show as they should which tells me it's something with PKC. And another wierd thing happens quite often is that movies disappear from "Latest movies" after a while, even though they are the latest addition and unwatched. But if I search for them I see them. The same goes for missing movies in collections. I can see them if I search. It's just some sort of indexing issue I feel.  Can someone else confirm that they are experiencing these issues?

**Comment by croneter** [comment]
@Nojahhh 
>And the wierd thing is that a movie thats missing in one collection might show up in another one that it is in. 
Kodi allows a movie to belong to exactly 0 or 1 collection. Plex allows for 0 to n collections. So there is currently NO way to replicate Plex 1:1 on the Kodi side. It's literally up to chance which collection a movie belongs to on the Kodi side of things, sorry... :disappointed: 

If you use PKCs search, which uses the Plex backend, then Yes collections are treated correctly.

**Comment by Nojahhh** [comment]
@croneter Ah, that explains it. Thank you a lot for such a quick and good response. A small price to pay for otherwise a great library! ;)

**Comment by rpattabi** [comment]
The same bug exists when creating and updating movie set using MediaElch (v2.6.6) as well. Adding new movie set and deleting movie sets, updating movie set with titles do not update the kodi db.

**Comment by amitgir** [comment]
Was this ever fixed or a new work-around suggested?
 
 TAGS were working just fine on Leia and v2 of PKC. But with Matrix and 3.X Kodi tags are now missing movies from my Plex Collections.

**Comment by moshstef** [comment]
> Was this ever fixed or a new work-around suggested?
> 
> TAGS were working just fine on Leia and v2 of PKC. But with Matrix and 3.X Kodi tags are now missing movies from my Plex Collections.

Yes I can also confirm that multiple tags are not working on v2.12.6. They are working on v2.12.3.

**Comment by newoski** [comment]
Apologies. I understand now. Reposting the related question here. 

Is there any way to automate/call the "repair database" function via cron/JSON etc?

**Comment by croneter** [comment]
Nope, @newoski , that's currently not possible via a "PKC API". Theoretically, you could just delete the [Kodi movie database file](https://kodi.wiki/view/Databases) when Kodi is not running. Plus the plex.db file, might be also a good idea. PKC will then re-sync everything.

**Comment by fnwc** [comment]
For anyone running into the same issue, I just solved this in my particular case. In my environment, it was caused by an errant (unrelated to PKC) addon. The result was some movies were searchable through the UI but not visible in the library view or in the set (I had several empty/incomplete movie sets/collections).

Looking in the log, I was getting

`2024-11-26 02:04:51.878 T:4069  warning <general>: PLEX.utils: User accepted risk of a non-default skin
2024-11-26 02:04:59.060 T:4139    error <general>: PLEX.websocket: pms_websocket: got an unexpected exception of type <class 'AttributeError'>: 'NoneType' object has no attribute 'is_ssl'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/websocket/_app.py", line 320, in run_forever
                                                       dispatcher = self.create_dispatcher(ping_timeout)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/websocket/_app.py", line 380, in create_dispatcher
                                                       if self.sock.is_ssl():
                                                          ^^^^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'is_ssl'
2024-11-26 02:04:59.675 T:4145    error <general>: PLEX.websocket: alexa_websocket: got an unexpected exception of type <class 'AttributeError'>: 'NoneType' object has no attribute 'is_ssl'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/websocket/_app.py", line 320, in run_forever
                                                       dispatcher = self.create_dispatcher(ping_timeout)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/websocket/_app.py", line 380, in create_dispatcher
                                                       if self.sock.is_ssl():
                                                          ^^^^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'is_ssl'
2024-11-26 02:05:15.136 T:4159  warning <general>: PLEX.sync.process_metadata: Sync not successful for section {'index': 1, 'name': 'Movies', 'section_id': 2, 'section_type': 'movie', 'plex_type': 'movie', 'sync_to_kodi': True, 'last_sync': None}
2024-11-26 02:05:50.445 T:4148    error <general>: PLEX.sync.fill_metadata_queue: Putting 1125195 in get_metadata_queue timed out - aborting sync now`

So I ended up just removing unnecessary my addons and force resetting fixed the issue.
