### ISSUE TITLE
 release 3.5.10 for Kodi 19.3 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by thantsg** [croneter/PlexKodiConnect#1696]
hello

i opened this because there's an issue and i want to give you all the info for this bug report but 

release 3.5.10 for Kodi 19.3 (corelec 19.3-Matrix) gives an error on playback. i believe it's 'bool' object has no attribute 'get'. downgrading to 3.5.9 resolves the issue and playback works. 

i love you sorry this bug report sucks

**Comment by Sparh4wk** [comment]
same error here

**Comment by Wally73** [comment]
same here in 3.5.10

**Comment by Cyriltra** [comment]
Also get same error since update to 3.5.10. This error is preventing any video file to play.

below some logs:
`2021-11-07 13:08:43.805 T:4842     INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-11-07 13:08:43.806 T:4842     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "surround71:CARD=AMLAUGESOUND,DEV=0"
2021-11-07 13:08:43.825 T:4842     INFO <general>: CAESinkALSA::Initialize - Opened device "surround71:CARD=AMLAUGESOUND,DEV=0"
2021-11-07 13:08:43.826 T:4842     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2021-11-07 13:08:43.826 T:4842     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE4
2021-11-07 13:08:43.835 T:6516     INFO <general>: initializing python engine.
2021-11-07 13:08:43.895 T:6516     INFO <general>: PLEX.TVSHOWS: PKC add-on for tv shows started
2021-11-07 13:08:44.148 T:6516     INFO <general>: PLEX.TVSHOWS: PKC add-on for tv shows stopped
2021-11-07 13:08:44.148 T:6516     INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.plexkodiconnect.tvshows/default.py): script successfully run
2021-11-07 13:08:44.180 T:4830    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.plexkodiconnect.tvshows/36784/?mode=play&plex_id=36819&plex_type=episode&filename=qqq.mkv]
2021-11-07 13:08:44.354 T:6516  WARNING <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.plexkodiconnect.tvshows/default.py): the python script "/storage/.kodi/addons/plugin.video.plexkodiconnect.tvshows/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2021-11-07 13:08:44.354 T:6516     INFO <general>: Python interpreter stopped
2021-11-07 13:08:44.434 T:6520     INFO <general>: initializing python engine.
2021-11-07 13:08:44.613 T:6520     INFO <general>: PLEX.TVSHOWS: PKC add-on for tv shows started
2021-11-07 13:08:44.779 T:5000     INFO <general>: PLEX.playback_decision: User chose playback method DirectPath in PKC settings
2021-11-07 13:08:45.035 T:5000     INFO <general>: PLEX.playback_decision: PKC decided on playback method DirectPlay
2021-11-07 13:08:45.035 T:5000     INFO <general>: PLEX.playback_decision: Lets ask the PMS next
2021-11-07 13:08:45.036 T:5000     INFO <general>: PLEX.playback_decision: Asking PMS with maximal quality settings
2021-11-07 13:08:45.061 T:5000  WARNING <general>: PLEX.download: Unknown answer from PMS https://192-168-50-13.33qqqqplex.direct:32400/video/:/transcode/universal/decision?path=%2Flibrary%2Fmetadata%2F36819&directPlay=1&directStream=1&directStreamAudio=1&hasMDE=1&mediaIndex=0&partIndex=0&audioBoost=0&autoAdjustQuality=0&protocol=hls&session=qqqq&fastSeek=1&copyts=1&maxVideoBitrate=2147483647&videoResolution=3840x2160&videoQuality=100&mediaBufferSize=20480&subtitles=none with status code 400: <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>
**2021-11-07 13:08:45.062 T:5000  WARNING <general>: PLEX.playback_decision: Could not find suitable settings for playback, aborting**
**2021-11-07 13:08:45.062 T:5000    ERROR <general>: PLEX.utils: Error encountered:  - 'bool' object has no attribute 'get'**
2021-11-07 13:08:45.062 T:5000    ERROR <general>: PLEX.utils: _____________________________________________________________
2021-11-07 13:08:45.062 T:5000    ERROR <general>: PLEX.utils:     Traceback (most recent call last):
2021-11-07 13:08:45.062 T:5000    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback_decision.py", line 37, in set_playurl
2021-11-07 13:08:45.062 T:5000    ERROR <general>: PLEX.utils:         _pms_playback_decision(api, item)
2021-11-07 13:08:45.062 T:5000    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback_decision.py", line 87, in _pms_playback_decision
2021-11-07 13:08:45.062 T:5000    ERROR <general>: PLEX.utils:         decision_api = _ask_pms(api, item)
2021-11-07 13:08:45.062 T:5000    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback_decision.py", line 146, in _ask_pms
2021-11-07 13:08:45.063 T:5000    ERROR <general>: PLEX.utils:         decision_api.general_play_decision_code(),
2021-11-07 13:08:45.063 T:5000    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_api/playback.py", line 34, in general_play_decision_code
2021-11-07 13:08:45.063 T:5000    ERROR <general>: PLEX.utils:         return cast(int, self.xml.get('generalDecisionCode'))
2021-11-07 13:08:45.063 T:5000    ERROR <general>: PLEX.utils:     AttributeError: 'bool' object has no attribute 'get'
2021-11-07 13:08:45.063 T:5000    ERROR <general>: PLEX.utils: _____________________________________________________________
2021-11-07 13:08:45.063 T:5000     INFO <general>: PLEX.playback_decision: The playurl for None is: None
2021-11-07 13:08:45.063 T:5000     INFO <general>: PLEX.playback: Did not get a playurl, aborting playback silently`

**Comment by frakki1986** [comment]
Same here. Kodi19.3, Nvidia shield pro. Downgrade to 3.5.9 solves the issue

**Comment by croneter** [comment]
PKC Beta version 3.5.11 should fix this, hopefully. Pushing the new binary out right now...

**Comment by croneter** [comment]
The PMS caches certain settings. So please upgrade PKC. Then close Kodi and wait for a couple of minutes. 

If that does not work after the update, try the PKC under `Advanced`, then `Generate a new unique device ID`. Restart Kodi.

**Comment by frakki1986** [comment]
> The PMS caches certain settings. So please upgrade PKC. Then close Kodi and wait for a couple of minutes.
> 
> If that does not work after the update, try the PKC under `Advanced`, then `Generate a new unique device ID`. Restart Kodi.

Thanks in advance. I will try this tonight.

**Comment by Wally73** [comment]
> PKC Beta version 3.5.11 should fix this, hopefully. Pushing the new binary out right now...

yeah it's fixed thx :)

**Comment by RemuxZaph** [comment]
fixed after updating to 3.5.11, generating a new unique device ID, and a reboot. Thanks @croneter.
