### ISSUE TITLE
Error when starting up Kodi, “init() got an unexpected keyword argument ‘item’”. 

### ISSUE THREAD

**Issue by kpmelvin** [croneter/PlexKodiConnect#886]
Since updating to 2.8.1 I see the following error when starting up Kodi, “init() got an unexpected keyword argument ‘item’”.

**Comment by kpmelvin** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3287959/kodi.log)

**Comment by croneter** [comment]
Should be solved in beta version 2.8.2. Please let me know

**Comment by kpmelvin** [comment]
Hi Croneter,

Looking good, no longer getting the error. You rock!!!

Thx, Ken
