### ISSUE TITLE
3.9.1 bug when playing media: 'Nonetype' object has no attribute 'setpath'

### ISSUE THREAD

**Issue by cyril88888** [croneter/PlexKodiConnect#2050]
Hello,

i have a bug since updating to 3.9.1 on coreelec 20.5: whenever i try to play a media i have: "Nonetype object has no attribute set path"
I tried restart and reset database (incl. app config), still the same

Here is my [log](https://paste.coreelec.org/uLJI26)

Thank you

**Comment by ryryonline** [comment]
I experienced the same issue this morning using the official Plex docker. I tried to roll back a few versions of the docker but still experiencing the same issue. [https://hub.docker.com/r/plexinc/pms-docker/tags](url)

**Comment by croneter** [comment]
@ryryonline using PKC version 3.9.0 should fix your issues. If not, please share your DEBUG logs: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
