### PR TITLE
Make PKC compatible with Python 3.6 again

### LINKED ISSUE #1688: No longer compatible with python 3.6
## Help yourself
Tried first.

## Describe the bug

plexkodiconnect does not sync due to a startup crash, starting at release 3.5.8
Error Contents: cannot import name 'ThreadingHTTPServer'

I only took a quick look but its probably introduced in this commit:
https://github.com/croneter/PlexKodiConnect/pull/1686/commits/f3754fa2e323fc3b6582c839f1fa46da9fbb3939

## To Reproduce
Install on Ubuntu 18.04 with kodi matrix or any linux system where python3.6 is the system default for python3

## Expected behavior
No exception on startup

## You need to attach a KODI LOG FILE!
2021-10-31 16:59:05.246 T:145     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'ThreadingHTTPServer'
                                                   Traceback (most recent call last):
                                                     File "/cfgfs/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 4, in <module>
                                                       from resources.lib import service_entry
                                                     File "/cfgfs/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 13, in <module>
                                                       from . import plex_companion
                                                     File "/cfgfs/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 12, in <module>
                                                       from .plexbmchelper import listener, plexgdm, subscribers, httppersist
                                                     File "/cfgfs/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plexbmchelper/listener.py", line 8, in <module>
                                                       from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
                                                   ImportError: cannot import name 'ThreadingHTTPServer'
                                                   -->End of Python script error report<--

### PR DESCRIPTION
**Pull request by croneter**
- Fixes #1688
- Regression introduced in #1674

### CODE REVIEW

**Comment by croneter** [comment]
Obsolete with PR #1687
